#!/usr/bin/env php
<?php

$autoload = dirname(dirname(dirname(dirname(__FILE__)))) .'/autoload.php';
if (file_exists($autoload)) {
    require $autoload;
} else {
    require dirname(dirname(__FILE__)) .'/vendor/autoload.php';
}

use DTOx\Console\DtoxCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new DtoxCommand);
$application->run();